
name: Deploy RAG

on:

  push:

    branches:

      - main

jobs:

  deploy:

    runs-on: ubuntu-latest

    steps:

      - name: Deploy rag

        uses: appleboy/ssh-action@master

        with:

          host: ${{ secrets.HOST }}

          username: ${{ secrets.USERNAME }}

          key: ${{ secrets.SSH_KEY }}

          port: ${{ secrets.PORT }}

          script: |

            export PATH=$PATH:/root/.nvm/versions/node/v24.15.0/bin

            cd /var/www/rag_chatbot

            git reset --hard

            git pull origin main

            npm install

            pm2 reload rag-chatbot || pm2 start npm --name rag-chatbot -- start

